// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package socketclient;

/**
 * Protobuf type {@code socketclient.Command}
 */
public final class Command extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:socketclient.Command)
    CommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Command.newBuilder() to construct.
  private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Command() {
    command_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Command();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Command(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            command_ = s;
            break;
          }
          case 18: {
            socketclient.Client.Builder subBuilder = null;
            if (msgCase_ == 2) {
              subBuilder = ((socketclient.Client) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(socketclient.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((socketclient.Client) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 2;
            break;
          }
          case 26: {
            socketclient.Music.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((socketclient.Music) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(socketclient.Music.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((socketclient.Music) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            socketclient.Light.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((socketclient.Light) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(socketclient.Light.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((socketclient.Light) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          case 42: {
            socketclient.Uro.Builder subBuilder = null;
            if (msgCase_ == 5) {
              subBuilder = ((socketclient.Uro) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(socketclient.Uro.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((socketclient.Uro) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 5;
            break;
          }
          case 50: {
            socketclient.NetworkCre.Builder subBuilder = null;
            if (msgCase_ == 6) {
              subBuilder = ((socketclient.NetworkCre) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(socketclient.NetworkCre.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((socketclient.NetworkCre) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return socketclient.UroCommand.internal_static_socketclient_Command_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return socketclient.UroCommand.internal_static_socketclient_Command_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            socketclient.Command.class, socketclient.Command.Builder.class);
  }

  private int bitField0_;
  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CLIENT(2),
    MUSIC(3),
    LIGHT(4),
    URO(5),
    NETWORK(6),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 2: return CLIENT;
        case 3: return MUSIC;
        case 4: return LIGHT;
        case 5: return URO;
        case 6: return NETWORK;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object command_;
  /**
   * <code>optional string command = 1;</code>
   * @return Whether the command field is set.
   */
  @java.lang.Override
  public boolean hasCommand() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string command = 1;</code>
   * @return The command.
   */
  @java.lang.Override
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>optional string command = 1;</code>
   * @return The bytes for command.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_FIELD_NUMBER = 2;
  /**
   * <code>.socketclient.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  @java.lang.Override
  public boolean hasClient() {
    return msgCase_ == 2;
  }
  /**
   * <code>.socketclient.Client client = 2;</code>
   * @return The client.
   */
  @java.lang.Override
  public socketclient.Client getClient() {
    if (msgCase_ == 2) {
       return (socketclient.Client) msg_;
    }
    return socketclient.Client.getDefaultInstance();
  }
  /**
   * <code>.socketclient.Client client = 2;</code>
   */
  @java.lang.Override
  public socketclient.ClientOrBuilder getClientOrBuilder() {
    if (msgCase_ == 2) {
       return (socketclient.Client) msg_;
    }
    return socketclient.Client.getDefaultInstance();
  }

  public static final int MUSIC_FIELD_NUMBER = 3;
  /**
   * <code>.socketclient.Music music = 3;</code>
   * @return Whether the music field is set.
   */
  @java.lang.Override
  public boolean hasMusic() {
    return msgCase_ == 3;
  }
  /**
   * <code>.socketclient.Music music = 3;</code>
   * @return The music.
   */
  @java.lang.Override
  public socketclient.Music getMusic() {
    if (msgCase_ == 3) {
       return (socketclient.Music) msg_;
    }
    return socketclient.Music.getDefaultInstance();
  }
  /**
   * <code>.socketclient.Music music = 3;</code>
   */
  @java.lang.Override
  public socketclient.MusicOrBuilder getMusicOrBuilder() {
    if (msgCase_ == 3) {
       return (socketclient.Music) msg_;
    }
    return socketclient.Music.getDefaultInstance();
  }

  public static final int LIGHT_FIELD_NUMBER = 4;
  /**
   * <code>.socketclient.Light light = 4;</code>
   * @return Whether the light field is set.
   */
  @java.lang.Override
  public boolean hasLight() {
    return msgCase_ == 4;
  }
  /**
   * <code>.socketclient.Light light = 4;</code>
   * @return The light.
   */
  @java.lang.Override
  public socketclient.Light getLight() {
    if (msgCase_ == 4) {
       return (socketclient.Light) msg_;
    }
    return socketclient.Light.getDefaultInstance();
  }
  /**
   * <code>.socketclient.Light light = 4;</code>
   */
  @java.lang.Override
  public socketclient.LightOrBuilder getLightOrBuilder() {
    if (msgCase_ == 4) {
       return (socketclient.Light) msg_;
    }
    return socketclient.Light.getDefaultInstance();
  }

  public static final int URO_FIELD_NUMBER = 5;
  /**
   * <code>.socketclient.Uro uro = 5;</code>
   * @return Whether the uro field is set.
   */
  @java.lang.Override
  public boolean hasUro() {
    return msgCase_ == 5;
  }
  /**
   * <code>.socketclient.Uro uro = 5;</code>
   * @return The uro.
   */
  @java.lang.Override
  public socketclient.Uro getUro() {
    if (msgCase_ == 5) {
       return (socketclient.Uro) msg_;
    }
    return socketclient.Uro.getDefaultInstance();
  }
  /**
   * <code>.socketclient.Uro uro = 5;</code>
   */
  @java.lang.Override
  public socketclient.UroOrBuilder getUroOrBuilder() {
    if (msgCase_ == 5) {
       return (socketclient.Uro) msg_;
    }
    return socketclient.Uro.getDefaultInstance();
  }

  public static final int NETWORK_FIELD_NUMBER = 6;
  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   * @return Whether the network field is set.
   */
  @java.lang.Override
  public boolean hasNetwork() {
    return msgCase_ == 6;
  }
  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   * @return The network.
   */
  @java.lang.Override
  public socketclient.NetworkCre getNetwork() {
    if (msgCase_ == 6) {
       return (socketclient.NetworkCre) msg_;
    }
    return socketclient.NetworkCre.getDefaultInstance();
  }
  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   */
  @java.lang.Override
  public socketclient.NetworkCreOrBuilder getNetworkOrBuilder() {
    if (msgCase_ == 6) {
       return (socketclient.NetworkCre) msg_;
    }
    return socketclient.NetworkCre.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, command_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (socketclient.Client) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (socketclient.Music) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (socketclient.Light) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (socketclient.Uro) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (socketclient.NetworkCre) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, command_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (socketclient.Client) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (socketclient.Music) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (socketclient.Light) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (socketclient.Uro) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (socketclient.NetworkCre) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof socketclient.Command)) {
      return super.equals(obj);
    }
    socketclient.Command other = (socketclient.Command) obj;

    if (hasCommand() != other.hasCommand()) return false;
    if (hasCommand()) {
      if (!getCommand()
          .equals(other.getCommand())) return false;
    }
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 2:
        if (!getClient()
            .equals(other.getClient())) return false;
        break;
      case 3:
        if (!getMusic()
            .equals(other.getMusic())) return false;
        break;
      case 4:
        if (!getLight()
            .equals(other.getLight())) return false;
        break;
      case 5:
        if (!getUro()
            .equals(other.getUro())) return false;
        break;
      case 6:
        if (!getNetwork()
            .equals(other.getNetwork())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommand()) {
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
    }
    switch (msgCase_) {
      case 2:
        hash = (37 * hash) + CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getClient().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MUSIC_FIELD_NUMBER;
        hash = (53 * hash) + getMusic().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getLight().hashCode();
        break;
      case 5:
        hash = (37 * hash) + URO_FIELD_NUMBER;
        hash = (53 * hash) + getUro().hashCode();
        break;
      case 6:
        hash = (37 * hash) + NETWORK_FIELD_NUMBER;
        hash = (53 * hash) + getNetwork().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static socketclient.Command parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static socketclient.Command parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static socketclient.Command parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static socketclient.Command parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static socketclient.Command parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static socketclient.Command parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static socketclient.Command parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static socketclient.Command parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static socketclient.Command parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static socketclient.Command parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static socketclient.Command parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static socketclient.Command parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(socketclient.Command prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code socketclient.Command}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:socketclient.Command)
      socketclient.CommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return socketclient.UroCommand.internal_static_socketclient_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return socketclient.UroCommand.internal_static_socketclient_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              socketclient.Command.class, socketclient.Command.Builder.class);
    }

    // Construct using socketclient.Command.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      command_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return socketclient.UroCommand.internal_static_socketclient_Command_descriptor;
    }

    @java.lang.Override
    public socketclient.Command getDefaultInstanceForType() {
      return socketclient.Command.getDefaultInstance();
    }

    @java.lang.Override
    public socketclient.Command build() {
      socketclient.Command result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public socketclient.Command buildPartial() {
      socketclient.Command result = new socketclient.Command(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.command_ = command_;
      if (msgCase_ == 2) {
        if (clientBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = clientBuilder_.build();
        }
      }
      if (msgCase_ == 3) {
        if (musicBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = musicBuilder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (lightBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = lightBuilder_.build();
        }
      }
      if (msgCase_ == 5) {
        if (uroBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = uroBuilder_.build();
        }
      }
      if (msgCase_ == 6) {
        if (networkBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = networkBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof socketclient.Command) {
        return mergeFrom((socketclient.Command)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(socketclient.Command other) {
      if (other == socketclient.Command.getDefaultInstance()) return this;
      if (other.hasCommand()) {
        bitField0_ |= 0x00000001;
        command_ = other.command_;
        onChanged();
      }
      switch (other.getMsgCase()) {
        case CLIENT: {
          mergeClient(other.getClient());
          break;
        }
        case MUSIC: {
          mergeMusic(other.getMusic());
          break;
        }
        case LIGHT: {
          mergeLight(other.getLight());
          break;
        }
        case URO: {
          mergeUro(other.getUro());
          break;
        }
        case NETWORK: {
          mergeNetwork(other.getNetwork());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      socketclient.Command parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (socketclient.Command) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object command_ = "";
    /**
     * <code>optional string command = 1;</code>
     * @return Whether the command field is set.
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string command = 1;</code>
     * @return The command.
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string command = 1;</code>
     * @return The bytes for command.
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      bitField0_ = (bitField0_ & ~0x00000001);
      command_ = getDefaultInstance().getCommand();
      onChanged();
      return this;
    }
    /**
     * <code>optional string command = 1;</code>
     * @param value The bytes for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      command_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Client, socketclient.Client.Builder, socketclient.ClientOrBuilder> clientBuilder_;
    /**
     * <code>.socketclient.Client client = 2;</code>
     * @return Whether the client field is set.
     */
    @java.lang.Override
    public boolean hasClient() {
      return msgCase_ == 2;
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     * @return The client.
     */
    @java.lang.Override
    public socketclient.Client getClient() {
      if (clientBuilder_ == null) {
        if (msgCase_ == 2) {
          return (socketclient.Client) msg_;
        }
        return socketclient.Client.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return clientBuilder_.getMessage();
        }
        return socketclient.Client.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    public Builder setClient(socketclient.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    public Builder setClient(
        socketclient.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    public Builder mergeClient(socketclient.Client value) {
      if (clientBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != socketclient.Client.getDefaultInstance()) {
          msg_ = socketclient.Client.newBuilder((socketclient.Client) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          clientBuilder_.mergeFrom(value);
        } else {
          clientBuilder_.setMessage(value);
        }
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        clientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    public socketclient.Client.Builder getClientBuilder() {
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    @java.lang.Override
    public socketclient.ClientOrBuilder getClientOrBuilder() {
      if ((msgCase_ == 2) && (clientBuilder_ != null)) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (socketclient.Client) msg_;
        }
        return socketclient.Client.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Client client = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Client, socketclient.Client.Builder, socketclient.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = socketclient.Client.getDefaultInstance();
        }
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            socketclient.Client, socketclient.Client.Builder, socketclient.ClientOrBuilder>(
                (socketclient.Client) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();;
      return clientBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Music, socketclient.Music.Builder, socketclient.MusicOrBuilder> musicBuilder_;
    /**
     * <code>.socketclient.Music music = 3;</code>
     * @return Whether the music field is set.
     */
    @java.lang.Override
    public boolean hasMusic() {
      return msgCase_ == 3;
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     * @return The music.
     */
    @java.lang.Override
    public socketclient.Music getMusic() {
      if (musicBuilder_ == null) {
        if (msgCase_ == 3) {
          return (socketclient.Music) msg_;
        }
        return socketclient.Music.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return musicBuilder_.getMessage();
        }
        return socketclient.Music.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    public Builder setMusic(socketclient.Music value) {
      if (musicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        musicBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    public Builder setMusic(
        socketclient.Music.Builder builderForValue) {
      if (musicBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        musicBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    public Builder mergeMusic(socketclient.Music value) {
      if (musicBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != socketclient.Music.getDefaultInstance()) {
          msg_ = socketclient.Music.newBuilder((socketclient.Music) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          musicBuilder_.mergeFrom(value);
        } else {
          musicBuilder_.setMessage(value);
        }
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    public Builder clearMusic() {
      if (musicBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        musicBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    public socketclient.Music.Builder getMusicBuilder() {
      return getMusicFieldBuilder().getBuilder();
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    @java.lang.Override
    public socketclient.MusicOrBuilder getMusicOrBuilder() {
      if ((msgCase_ == 3) && (musicBuilder_ != null)) {
        return musicBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (socketclient.Music) msg_;
        }
        return socketclient.Music.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Music music = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Music, socketclient.Music.Builder, socketclient.MusicOrBuilder> 
        getMusicFieldBuilder() {
      if (musicBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = socketclient.Music.getDefaultInstance();
        }
        musicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            socketclient.Music, socketclient.Music.Builder, socketclient.MusicOrBuilder>(
                (socketclient.Music) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return musicBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Light, socketclient.Light.Builder, socketclient.LightOrBuilder> lightBuilder_;
    /**
     * <code>.socketclient.Light light = 4;</code>
     * @return Whether the light field is set.
     */
    @java.lang.Override
    public boolean hasLight() {
      return msgCase_ == 4;
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     * @return The light.
     */
    @java.lang.Override
    public socketclient.Light getLight() {
      if (lightBuilder_ == null) {
        if (msgCase_ == 4) {
          return (socketclient.Light) msg_;
        }
        return socketclient.Light.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return lightBuilder_.getMessage();
        }
        return socketclient.Light.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    public Builder setLight(socketclient.Light value) {
      if (lightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        lightBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    public Builder setLight(
        socketclient.Light.Builder builderForValue) {
      if (lightBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        lightBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    public Builder mergeLight(socketclient.Light value) {
      if (lightBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != socketclient.Light.getDefaultInstance()) {
          msg_ = socketclient.Light.newBuilder((socketclient.Light) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          lightBuilder_.mergeFrom(value);
        } else {
          lightBuilder_.setMessage(value);
        }
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    public Builder clearLight() {
      if (lightBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        lightBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    public socketclient.Light.Builder getLightBuilder() {
      return getLightFieldBuilder().getBuilder();
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    @java.lang.Override
    public socketclient.LightOrBuilder getLightOrBuilder() {
      if ((msgCase_ == 4) && (lightBuilder_ != null)) {
        return lightBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (socketclient.Light) msg_;
        }
        return socketclient.Light.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Light light = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Light, socketclient.Light.Builder, socketclient.LightOrBuilder> 
        getLightFieldBuilder() {
      if (lightBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = socketclient.Light.getDefaultInstance();
        }
        lightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            socketclient.Light, socketclient.Light.Builder, socketclient.LightOrBuilder>(
                (socketclient.Light) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return lightBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Uro, socketclient.Uro.Builder, socketclient.UroOrBuilder> uroBuilder_;
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     * @return Whether the uro field is set.
     */
    @java.lang.Override
    public boolean hasUro() {
      return msgCase_ == 5;
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     * @return The uro.
     */
    @java.lang.Override
    public socketclient.Uro getUro() {
      if (uroBuilder_ == null) {
        if (msgCase_ == 5) {
          return (socketclient.Uro) msg_;
        }
        return socketclient.Uro.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return uroBuilder_.getMessage();
        }
        return socketclient.Uro.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    public Builder setUro(socketclient.Uro value) {
      if (uroBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        uroBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    public Builder setUro(
        socketclient.Uro.Builder builderForValue) {
      if (uroBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        uroBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    public Builder mergeUro(socketclient.Uro value) {
      if (uroBuilder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != socketclient.Uro.getDefaultInstance()) {
          msg_ = socketclient.Uro.newBuilder((socketclient.Uro) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          uroBuilder_.mergeFrom(value);
        } else {
          uroBuilder_.setMessage(value);
        }
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    public Builder clearUro() {
      if (uroBuilder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        uroBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    public socketclient.Uro.Builder getUroBuilder() {
      return getUroFieldBuilder().getBuilder();
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    @java.lang.Override
    public socketclient.UroOrBuilder getUroOrBuilder() {
      if ((msgCase_ == 5) && (uroBuilder_ != null)) {
        return uroBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (socketclient.Uro) msg_;
        }
        return socketclient.Uro.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.Uro uro = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.Uro, socketclient.Uro.Builder, socketclient.UroOrBuilder> 
        getUroFieldBuilder() {
      if (uroBuilder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = socketclient.Uro.getDefaultInstance();
        }
        uroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            socketclient.Uro, socketclient.Uro.Builder, socketclient.UroOrBuilder>(
                (socketclient.Uro) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();;
      return uroBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.NetworkCre, socketclient.NetworkCre.Builder, socketclient.NetworkCreOrBuilder> networkBuilder_;
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     * @return Whether the network field is set.
     */
    @java.lang.Override
    public boolean hasNetwork() {
      return msgCase_ == 6;
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     * @return The network.
     */
    @java.lang.Override
    public socketclient.NetworkCre getNetwork() {
      if (networkBuilder_ == null) {
        if (msgCase_ == 6) {
          return (socketclient.NetworkCre) msg_;
        }
        return socketclient.NetworkCre.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return networkBuilder_.getMessage();
        }
        return socketclient.NetworkCre.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    public Builder setNetwork(socketclient.NetworkCre value) {
      if (networkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        networkBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    public Builder setNetwork(
        socketclient.NetworkCre.Builder builderForValue) {
      if (networkBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        networkBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    public Builder mergeNetwork(socketclient.NetworkCre value) {
      if (networkBuilder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != socketclient.NetworkCre.getDefaultInstance()) {
          msg_ = socketclient.NetworkCre.newBuilder((socketclient.NetworkCre) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          networkBuilder_.mergeFrom(value);
        } else {
          networkBuilder_.setMessage(value);
        }
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    public Builder clearNetwork() {
      if (networkBuilder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        networkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    public socketclient.NetworkCre.Builder getNetworkBuilder() {
      return getNetworkFieldBuilder().getBuilder();
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    @java.lang.Override
    public socketclient.NetworkCreOrBuilder getNetworkOrBuilder() {
      if ((msgCase_ == 6) && (networkBuilder_ != null)) {
        return networkBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (socketclient.NetworkCre) msg_;
        }
        return socketclient.NetworkCre.getDefaultInstance();
      }
    }
    /**
     * <code>.socketclient.NetworkCre network = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        socketclient.NetworkCre, socketclient.NetworkCre.Builder, socketclient.NetworkCreOrBuilder> 
        getNetworkFieldBuilder() {
      if (networkBuilder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = socketclient.NetworkCre.getDefaultInstance();
        }
        networkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            socketclient.NetworkCre, socketclient.NetworkCre.Builder, socketclient.NetworkCreOrBuilder>(
                (socketclient.NetworkCre) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();;
      return networkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:socketclient.Command)
  }

  // @@protoc_insertion_point(class_scope:socketclient.Command)
  private static final socketclient.Command DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new socketclient.Command();
  }

  public static socketclient.Command getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Command>
      PARSER = new com.google.protobuf.AbstractParser<Command>() {
    @java.lang.Override
    public Command parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Command(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Command> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Command> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public socketclient.Command getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

