// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UroCommand.proto

package socketclient;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:socketclient.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string command = 1;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>optional string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>.socketclient.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.socketclient.Client client = 2;</code>
   * @return The client.
   */
  socketclient.Client getClient();
  /**
   * <code>.socketclient.Client client = 2;</code>
   */
  socketclient.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.socketclient.Music music = 3;</code>
   * @return Whether the music field is set.
   */
  boolean hasMusic();
  /**
   * <code>.socketclient.Music music = 3;</code>
   * @return The music.
   */
  socketclient.Music getMusic();
  /**
   * <code>.socketclient.Music music = 3;</code>
   */
  socketclient.MusicOrBuilder getMusicOrBuilder();

  /**
   * <code>.socketclient.Light light = 4;</code>
   * @return Whether the light field is set.
   */
  boolean hasLight();
  /**
   * <code>.socketclient.Light light = 4;</code>
   * @return The light.
   */
  socketclient.Light getLight();
  /**
   * <code>.socketclient.Light light = 4;</code>
   */
  socketclient.LightOrBuilder getLightOrBuilder();

  /**
   * <code>.socketclient.Uro uro = 5;</code>
   * @return Whether the uro field is set.
   */
  boolean hasUro();
  /**
   * <code>.socketclient.Uro uro = 5;</code>
   * @return The uro.
   */
  socketclient.Uro getUro();
  /**
   * <code>.socketclient.Uro uro = 5;</code>
   */
  socketclient.UroOrBuilder getUroOrBuilder();

  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   * @return Whether the network field is set.
   */
  boolean hasNetwork();
  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   * @return The network.
   */
  socketclient.NetworkCre getNetwork();
  /**
   * <code>.socketclient.NetworkCre network = 6;</code>
   */
  socketclient.NetworkCreOrBuilder getNetworkOrBuilder();

  public socketclient.Command.MsgCase getMsgCase();
}
